language: generic

matrix:
  include:
    - os: linux
      env: COMPILER=4.02.3
    - os: linux
      env: COMPILER=4.08.0
    - os: osx
      env: COMPILER=4.08.0

before_script:
  - set -e
  - bash test/travis-install-opam.sh
  - eval `opam env`
  - ocamlc -config
  - opam --version
  - ocaml -version
  - cc --version || true
  - gcc --version || true
  - clang --version || true
  - opam pin add -y --no-action luv .
  - opam install -y --deps-only luv

script:
  - make
  - make test
  - make test-examples
  - make test-installation
  - opam lint .

cache:
  directories:
    - $HOME/.opam
    - ./_opam

notifications:
  email:
    recipients:
      - antonbachin@yahoo.com
    on_success: always
    on_failure: always
