language: generic

matrix:
  include:
    - os: linux
      env: COMPILER=4.02.3
    - os: linux
      env: COMPILER=4.08.1
    - os: osx
      env: COMPILER=4.08.1

before_script:
  - bash test/travis-install-opam.sh
  - eval `opam env`
  - ocamlc -config
  - opam --version
  - ocaml -version
  - cc --version || true
  - gcc --version || true
  - clang --version || true
  - opam pin add -y --dev-repo bisect_ppx
  - opam install -y --deps-only ./luv.opam

script:
  - make
  - make test
  - make test-examples
  - make test-installation
  - opam lint .

before_cache:
  - opam clean

cache:
  directories:
    - $HOME/.opam
    - ./_opam

notifications:
  email:
    on_success: always
    on_failure: always
