language: generic

matrix:
  include:
    - os: linux
      env: COMPILER=4.02.3 REVDEPS=yes
    - os: linux
      env: COMPILER=4.08.1
    - os: osx
      env: COMPILER=4.08.1

before_script:
  - bash test/travis-install-opam.sh
  - eval `opam env`
  - ocamlc -config
  - opam --version
  - ocaml -version
  - cc --version || true
  - gcc --version || true
  - clang --version || true
  - '[ -d _cache/_build ] || opam pin add -y --dev-repo bisect_ppx'
  - '[ -d _cache/_build ] || opam install -y --deps-only ./luv.opam'

script:
  - '[ ! -d _cache/_build ] || cp -r _cache/_build .'
  - make test-ci
  - '[ "$REVDEPS" != yes ] || make test-examples'
  - mkdir -p _cache
  - '[ -d _cache/_build ] || cp -r _build _cache'
  - '[ "$REVDEPS" != yes ] || make test-installation-ci'
  - opam lint .

before_cache:
  - opam clean
  - rm -rf _opam/.opam-switch/sources/bisect_ppx

cache:
  directories:
    - $HOME/.opam
    - ./_opam
    - ./_cache

notifications:
  email:
    on_success: always
    on_failure: always
